(tests
 (names t1 t_core t_debug)
 (modules t1 t_core t_debug)
 (package trace-tef)
 (libraries trace trace-tef))

(test
 (name t2)
 (package ppx_trace)
 (modules t2)
 (preprocess
  (pps ppx_trace))
 (libraries trace-tef))

(test
 (name t_runtime_events)
 (package trace-runtime-events)
 (modules t_runtime_events)
 (preprocess
  (pps ppx_trace))
 (libraries trace trace-runtime-events runtime_events))
