(executables
 (names t1 t2 t_debug t_core)
 (modules t1 t2 t_debug t_core)
 (libraries trace))

(executables
 (names t_runtime_events)
 (modules t_runtime_events)
 (enabled_if
  (>= %{ocaml_version} 5))
 (libraries trace trace.runtime-events))

(rule
 (target t_core.output)
 (action
  (with-stdout-to
   t_core.output
   (run %{exe:t_core.exe}))))

(rule
 (alias runtest)
 (action
  (diff t_core.expected t_core.output)))
